networks:
  gokit:

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus-config.yml
    command:
      - "--config.file=/etc/prometheus/prometheus-config.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - gokit

  loki:
    image: grafana/loki
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    command: 
      - "-config.file=/etc/loki/loki-config.yml"
    ports:  
      - 3100:3100
    networks:
      - gokit

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - gokit

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    networks:
      - gokit

  priceservice01:
    build: 
      context: app
    ports: 
      - 8081:8080
    networks:
      - gokit

  priceservice02:
    build: 
      context: app
    ports: 
      - 8082:8080
    networks:
      - gokit

  priceservice03:
    build: 
      context: app
    ports: 
      - 8083:8080
    networks:
      - gokit
